# Generated by Django 5.0.3 on 2024-03-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=192)),
                ('img', models.ImageField(upload_to='uploads/')),
                ('description', models.CharField(max_length=300)),
                ('year', models.IntegerField(max_length=4)),
                ('genre', models.CharField(max_length=120)),
                ('director', models.CharField(max_length=120)),
            ],
        ),
    ]
