# Generated by Django 5.0.3 on 2024-03-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumb_app', '0004_alter_movie_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=192)),
                ('img', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=120)),
                ('director', models.CharField(max_length=120)),
                ('comments', models.ManyToManyField(related_name='anime_comments', to='plumb_app.comment')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='comments',
            field=models.ManyToManyField(related_name='movie_comments', to='plumb_app.comment'),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=192)),
                ('img', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=120)),
                ('director', models.CharField(max_length=120)),
                ('comments', models.ManyToManyField(related_name='series_comments', to='plumb_app.comment')),
            ],
        ),
    ]
