# Generated by Django 5.0.3 on 2024-04-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumb_app', '0005_comment_news_alter_movie_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='comments',
            field=models.ManyToManyField(null=True, related_name='movie_comments', to='plumb_app.comment'),
        ),
    ]
