# Generated by Django 5.0.3 on 2024-04-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumb_app', '0006_alter_movie_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='movie_comments', to='plumb_app.comment'),
        ),
    ]
